# Site settings
title: "Dmitri Pisarev"
moto: "Web development with Love"
email: dimaip@gmail.com
description: "Reflections on modern web development techniques."
baseurl: ""
url: "http://dimaip.tumblr.com"
twitter_username: dimaip
github_username:  dimaip
host: server.psmb.ru

sass:
  style: :expanded # You might prefer to minify using :compressed

# Build settings
markdown: kramdown
permalink: pretty

analytics :
  provider : google
  google : 
      tracking_id : 'UA-52948019-1'
